DROP TABLE IF EXISTS author CASCADE;  

CREATE TABLE author
(
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar (64) NOT NULL,
	UNIQUE (name),
	PRIMARY KEY (id)
);

INSERT INTO author(name) VALUES
('John Smith');