DROP TABLE IF EXISTS issue_status CASCADE;  

CREATE TABLE issue_status
(
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar (64) NOT NULL DEFAULT 'Created',
	UNIQUE (name),
	PRIMARY KEY (id)
);

INSERT INTO issue_status(name) VALUES
('Created'),
('Closed'),
('Resolved');