DROP TABLE IF EXISTS issue_comment CASCADE;  

CREATE TABLE issue_comment
(
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	issue_id int NOT NULL,
	author_id int NOT NULL,
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status_id int NOT NULL,
	comment_text varchar(256) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (issue_id) REFERENCES issue(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (status_id) REFERENCES issue_status(id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO issue_comment(issue_id, author_id, status_id, comment_text) VALUES
(1, 1, 3, 'Error was in security component. Fixed in revision 123.');