DROP TABLE IF EXISTS issue CASCADE;  

CREATE TABLE issue
(
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar(128) NOT NULL,	
	description varchar(256) NOT NULL,
	start_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	author_id int NOT NULL,
	status_id int NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (status_id) REFERENCES issue_status(id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO issue(name, description, author_id, status_id) VALUES
('Internal error in annual PDF report', 'Annual financial report always return internal error to user. It’s work on previous release.', 1, 1);